/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package avaliacao.semestral;

public class App {
    

    public static void main(String[] args) throws Exception {
        
        PaymentProviderFactory paymentProviderFactory =  new PaymentProviderFactory();
        AgenteLogisticoFactory agenteLogisticoFactory = new AgenteLogisticoFactory();
        ProdutoFactory produtoFactory = new ProdutoFactory();
        Carrinho carrinho = new Carrinho();

        ProdutoQuantidade produtoQuantidade = produtoFactory.getProduto("Bicicleta", 630.90, 1);
        carrinho.addProdutos(produtoQuantidade);
        
                
        iPaymentProvider paymentProvider = paymentProviderFactory.getPaymentProvider("Mastercard");
            
        paymentProvider.pagar();

        Ecommerce ecommerce = new Ecommerce(paymentProvider, carrinho);

        iAgenteLogistico agenteLogistico = agenteLogisticoFactory.getAgenteLogistico("Correios", "Rua Izaltino dias Ferraz, 404", ecommerce);

        agenteLogistico.entregar();
        agenteLogistico.cancelar();
    }
}
